---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db-service
    author: anil
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    author: anil
...