---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    name: anil
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-pod
    author: anil
...