---
apiVersion: v1
kind: Pod
metadata:
  name: voting-app
  labels:
    name: voting-app
    author: anil
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
      - containerPort: 80
...